### ISSUE TITLE
Feature request: Option to suggest only on vertical and horizontal "snap"

### ISSUE THREAD

**Issue by DenysMb** [emvaized/kde-snap-assist#11]
Hello. Fist of all, great work!
I think that would be nice to have an option to suggest other windows only on vertical and horizontal "snap".
On Windows, when you try the "quarter layout" (snap window to upper left, upper right, bottom left or bottom right) it not suggest you other windows.

**Comment by emvaized** [comment]
Thanks! 
What is the rationale for introducing this option, except that there is no such thing in the Windows assistant?

**Comment by emvaized** [comment]
Closing this, as I don't see any reason for adding such an option. 
Perhaps in future versions there will be layout editor, with which you will be able to delete unneeded layouts.
