### ISSUE TITLE
Maximized windows that are tiled don't get set to windowed

### ISSUE THREAD

**Issue by mdl48** [emvaized/kde-snap-assist#19]
I use the kwin option "BorderlessMaximizedWindows" with the window buttons plasmoid.
When a maximized window gets tiled the maximized state is not set to windowed for those windows, due to that the window doesn't get the border back.
I tried adding `client.visibility = Window.Windowed;` in the function `selectClient` but it didn't work, I am not sure if in that function the window gets tiled.
The attachment is a video showcasing the problem.
https://user-images.githubusercontent.com/111306180/184692971-255d2cf5-49a3-49c4-9177-3f5c191ec0d5.mp4

**Comment by emvaized** [comment]
Hi! Thanks for your report.
I can see why it can happen – the script only modifies window's size and position, so it's quite expectable for tiled window to keep it's borderless state.

Yes, `selectClient()` is the exact function in which the selected window gets tiled. However, I could not find anything about `client.visibility` attribute in the KWin scripting's [documentation](https://develop.kde.org/docs/extend/plasma/kwin/api/). 

Maybe adding `client.noBorder = false;` line could help?

**Comment by mdl48** [comment]
I fixed the problem, in the kwin documentation there's a function setMaximize for clients. Just using that before resizing fixed it.
I will submit a pull request, so feel free to merge it.
Also thanks for the quick response!
