### ISSUE TITLE
Issue with using keyboard to enter quarter tiling

### ISSUE THREAD

**Issue by r-flash** [emvaized/kde-snap-assist#21]
First of all, thanks for this amazing script!

There is just this small issue with the (relatively new) KWin shortcut to enter quarter tiling. When you want to place the active window to, let's say, the top left quarter, you would normally press Meta and then hit Top and Left arrows in rapid succession. However, the Snap Assist is triggered right after pressing Meta+Top and the following Left arrow is not registered.

I don't know what kind of solution is feasible but maybe adding a small delay before triggering the Snap Assist would be enough?

**Comment by emvaized** [comment]
How, that's sounds reasonable. I suppose that adding default delay of 20ms could solve your problem, while not affecting regular usage so much.

I just added new config "delay before showing the assist" in the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev). 
Would be glad if you could test it! [Installation guide](https://github.com/emvaized/kde-snap-assist/tree/dev#manual-installation)

**Comment by r-flash** [comment]
Thanks! I tested it and it doesn't really seem to do anything. I set it to 1000ms but it still appears instantly. Does it mean I did something wrong? However, I checked `contents/ui/code/windows.js` in my downloaded zip and it does include the `setTimeout` call from the latest [change in the dev branch](https://github.com/emvaized/kde-snap-assist/commit/442404d41ca7b8371e200a15372906b5267c1822).

**Comment by emvaized** [comment]
It definitely should include that call. 
When I pushed the changes associated with this new option, I forgot to include it, and added it afterwards. Maybe you downloaded the zip file before I added the "missing method"? Please try to download the zip file again

**Comment by r-flash** [comment]
I double-checked and definitely have the latest commit. What is interesting is that when I went to `~/.local/share/kwin/scripts/kdesnapassist/contents/ui/code/windows.js`, manually changed the code to:
```js
                timer.setTimeout(function(){
                    onWindowResize(client);
                }, 1000); // changed to 1000 from delayBeforeShowingAssist
```
...and restarted KWin, it worked! So it might be a problem with the property? Maybe it's set to the default 20ms for some reason? Since the condition passes, it is not zero.

**Comment by emvaized** [comment]
Oh, it's my bad — I just specified this config as a `bool` type, when it obviously should be `int`. Should be working now!

**Comment by r-flash** [comment]
Works great now, thanks a lot for the quick responses!
