### ISSUE TITLE
KDE Snap Assist suggests windows from other activities

### ISSUE THREAD

**Issue by rodrigopedra** [emvaized/kde-snap-assist#23]
First, thanks for this wonderful script =)

When one is using more than one activity, KDE Snap Assist suggests windows present in other activities.

In addition, if one chose a window from another activity, its icon is not migrated to the current activity.

Just to be clear, I expected windows from another activity to not be available at all, I just wanted to share the behavior if one is selected.

**Comment by emvaized** [comment]
Thanks for your report. 
Sure, it makes total sense to filter out windows from other activities. And I believe there's no config needed for this, as it's the main purpose of activities itself.
I'll check what could be done.

**Comment by emvaized** [comment]
This thing turned out to be more difficult than I expected. [KWin Scripting API](https://develop.kde.org/docs/extend/plasma/kwin/api/) I has a property `activities`, which should list all the activities the window currently is on. But during my tests, it somehow always returns empty list, even for windows opened on another activity and not visible in the current one.

Maybe you could mention some other KWin scripts which do filtering by activities, so that we could take a look how they do it under the hood?

**Comment by rodrigopedra** [comment]
Thanks for the response @emvaized 

I don't have any other KWin scripts installed. If I find one which filters activities I will link it here

**Comment by emvaized** [comment]
I have implemented some test support for filtering out windows from other activities in the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev) — would be glad if you could try it out! 
([installation guide](https://github.com/emvaized/kde-snap-assist/tree/dev#manual-installation))

The script is set to display windows which are either visible on all activities, or which belong to the current activity only. 
_Note_: During my testing, restarting KWin or re-login to Plasma somehow resets the status for windows from other activities, and they may need to be reopened to be filtered out by the script correctly.

**Comment by emvaized** [comment]
However, I don't think it can get any better. I did more tests, and can confirm that assist now shows only windows visible on all activities, or those visible only on the current one, filtering out all the others.

The fix now is on the `main` branch and included in the new 1.5 release.

**Comment by rodrigopedra** [comment]
thanks @emvaized , it works much better now =)
