### ISSUE TITLE
Setting Menu is Too Big For Small Resolution

### ISSUE THREAD

**Issue by semarainc** [emvaized/kde-snap-assist#25]
Hi
I would like to report issue regarding setting menu for snap assists, the setting menu is too big for my laptop screen (1366x768)

This is the screenshot for the setting menu

![image](https://user-images.githubusercontent.com/19622207/185573940-86c1cd99-a054-4603-8b36-79011f62e314.png)

I hope you can make it so it can adapt for small screen resolution
Thanks :D

**Comment by emvaized** [comment]
I could not reproduce this issue on my setup with the same resolution, on Plasma 5.25.2.
![illustration](https://user-images.githubusercontent.com/37851576/185606907-da8f465a-ec0c-48fa-b698-768a5437599d.png)

Maybe you're using floating panel on bottom, which results in system ignoring it's height for new windows?

**Comment by semarainc** [comment]
Sorry i forgot to mention my Plasma version
currently i'm using plasma 5.24.6
This issue is affecting master and dev branch

**Comment by emvaized** [comment]
So, you must be using auto-hide settings for the panel on bottom?

**Comment by semarainc** [comment]
about that i'm not using auto-hide on my panel :(

**Comment by semarainc** [comment]
My laptop spec for better information and tracking

> Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.17.15-1-MANJARO (64-bit)
Graphics Platform: Wayland

**Comment by emvaized** [comment]
Hm, once you've mentioned that you're on Wayland, I managed to reproduce this issue only on Wayland session. 
Not sure however, if there's something I can do about it.

**Comment by emvaized** [comment]
I slightly changed the configs page layout in the latest [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev), so that it should use less vertical space, and should no longer cause overflow in your case.

**Comment by semarainc** [comment]
Hi 
yes, the current config menu is better than before :D
i love the current style :D
![image](https://user-images.githubusercontent.com/19622207/185779944-e6b256bd-e9a3-47e3-ac06-632c334abf32.png)

Thank You again for fixing this issue :D
