### ISSUE TITLE
Integrate sticky resize into the extension.

### ISSUE THREAD

**Issue by developer91234** [emvaized/kde-snap-assist#27]
The sticky windows extension hasn't been updated in over a year, so it doesn't make much sense to rely on a dead third party project to deliver the full functionality of the Windows snap assist feature. I would suggest just integrating it into the project and maybe improving it a little (the sticky window extension was pretty flaky last time I tried it: the behavior was very unreliable and the transparent windows UI was a bizarre choice)

**Comment by emvaized** [comment]
I follow the idea that a script should be dedicated to a single purpose, unless it's really reasoned to include some unrelated stuff in it – the way I recently did with new "enhanced" snap groups features (ended up not working on Wayland though). 

Sticky Window Snapping script works perfectly fine for me – especially in conjunction with this script – and for now I see no single reason to duplicate it's functionality here, thus increasing the maintenance burden.

**Comment by developer91234** [comment]
It has this silly transparency feature by default and the windows end up sticking to to other windows that you can't even see, even non-tiled ones. 

Maybe it has changed since the last time I tried it but it's clearly a complete UX disaster. If you use this feature on Gnome or Windows, it just works.

**Comment by emvaized** [comment]
If you're not satisfied with some specific parts of the script behavior, it's much easier to improve it by suggesting the changes, other than rewrite the whole thing. This script has been developed for years, with some great minds behind it, and if it doesn't work well for you – I am highly doubtful that I can do it any better.

By the way, the script has settings to disable the transparency effect which you don't like, and it also has an open [pull request](https://github.com/Flupp/sticky-window-snapping/pull/3)  which could solve the overlapping issue you mentioned, but the author did not proceed to work on it after the developer's commentary.

So, as said above, I currently see no reasons to include this functionality – but may reconsider it in the future.
