### ISSUE TITLE
Increase default opacity

### ISSUE THREAD

**Issue by developer91234** [emvaized/kde-snap-assist#28]
The transparency setting is set too high in my opinion and this makes the white text labels hard to read (also makes the whole interface less legible). I suggest something like 200 alpha for the default instead of 50. Obviously users can set it how they like but higher opacity would be better for most IMO.

**Comment by emvaized** [comment]
The reasoning behind the default transparency is that I wanted to make the assist the most unobtrusive as possible. 

But we probably could increase the default value of "50" to be at least "100". Actually, when I initially made this value "50", I thought it was by 100% scale, and not by 240 :D

**Comment by emvaized** [comment]
Default assist background opacity was increased in new version 1.5
