### ISSUE TITLE
[Feature Request] Autoresize without asking the user

### ISSUE THREAD

**Issue by Terkyz** [emvaized/kde-snap-assist#32]
An option to automatically resize windows without prompting the user could be useful, for example, if I have two 1/2 windows, I just want that, 1/2, I don't have any more windows open so I don't need KDE Snap Assistand asked me how I want to arrange my windows

**Comment by emvaized** [comment]
Well, if I understood your request correctly, this is something I already have in work under the [dev](https://github.com/emvaized/kde-snap-assist/tree/dev) branch, as an extension to already existing "snap groups" features. The feature is called "Try to fit snapped window in group behind it", and you can read more about the idea behind it [here](https://github.com/emvaized/kde-snap-assist/issues/5#issuecomment-1221619989).

However, the thing is quite unstable now, requires "Raise snapped windows together" feature enables, and relies on last activation time to determine if there's an active snap group behind the newly snapped window.

Few examples of it in work:

![two-windows-snap](https://user-images.githubusercontent.com/37851576/186278627-269b91b3-81db-496f-a4cc-a5991b5c7086.gif)

![fit-in-group-behind](https://user-images.githubusercontent.com/37851576/186279058-48e27c07-e232-4e4d-bc34-a4a2e2d0a508.gif)
