### ISSUE TITLE
Main window is not transparent

### ISSUE THREAD

**Issue by vpsone** [emvaized/kde-snap-assist#33]
![image](https://user-images.githubusercontent.com/84894255/187026554-6f03b30d-da55-4891-96db-f2b9c551d2ba.png)
### OS info
![image](https://user-images.githubusercontent.com/84894255/187026621-7e9c6403-5e71-4dd2-9022-23c27ed08d2e.png)

**Comment by emvaized** [comment]
Do you have KWin effects disabled in your system? As it may result in transparency effects not being applied.
If not, what happens if you try to change the background color and it's opacity from the script settings?

**Comment by vpsone** [comment]
I am not able to change any color.
![image](https://user-images.githubusercontent.com/84894255/187039437-52f632d4-ac13-4e33-8e83-f6b5a01b3b43.png)

**Comment by vpsone** [comment]
In my kwinrc file, this is present.

```
[Script-kdesnapassist]
backdropColor=false
borderRadius=8
cardColor=false
hoveredCardColor=false
textColor=false
```

**Comment by emvaized** [comment]
Then it must be the same issue as reported [before](https://github.com/emvaized/kde-snap-assist/issues/7). I have no idea why a boolean value `false` gets set for the string color values, and never saw it happen on my computer. 

Maybe it's some Plasma bug, as the logic behind connecting settings with corresponding stored config gets handled by the system itself under the hood.

**Comment by emvaized** [comment]
I just added small change in the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev), which ensures that the default colors will be used in case the stored values were read as `false`. It does not solve the issue of these configs being set this way in the first place, but at least will ensure the script remains usable.

**Comment by vpsone** [comment]
If i delete this part from kwinrc
https://github.com/emvaized/kde-snap-assist/issues/33#issuecomment-1229226767
After rebooting, Main view gets transparent. 
![image](https://user-images.githubusercontent.com/84894255/187065871-cb0587da-7490-4fc9-8fa1-fe28816f5601.png)
But if i open setting and try to change anything after saving. it's get black as previously
![image](https://user-images.githubusercontent.com/84894255/187065732-8adaec33-5ed6-4811-99de-6e78072719ab.png)
I also tried your solution https://github.com/emvaized/kde-snap-assist/issues/33#issuecomment-1229283450 but it is not working.

**Comment by emvaized** [comment]
You mean, after installing the `dev` version and rebooting the "black background" issue still happens?

**Comment by emvaized** [comment]
I rewrote this patch now, so now it should be def. working
