### ISSUE TITLE
kde-snap-assist interrupts KDE's normal snap shortcuts

### ISSUE THREAD

**Issue by doncsugar** [emvaized/kde-snap-assist#39]
When snapping windows without kde-snap-assist, windows can be corner tiled by pressing `meta + right arrow` followed by `meta + up arrow` or vice versa (`meta + up arrow` followed by `meta + right arrow`). When kde-snap-assist is active, it interrupts the first tile operation and prevents the second one that would move a window to a corner. The user has to first hit `esc` to close kde-snap-assist to tile it normally.

I think kde-snap-assist could:

- ignore arrow key presses that include `meta` and allow the normal KDE tiling. If only arrow keys are pressed, kde-snap-assist can move through currently open windows as usual
- add a delay before it shows itself to allow for time to snap a window into the desired position

**Comment by emvaized** [comment]
This option already exists in the script's settings since version 1.4 or so. It's called "Delay before showing the assist"
