### ISSUE TITLE
Multiple monitors support

### ISSUE THREAD

**Issue by Victor239** [emvaized/kde-snap-assist#40]
I use two monitors, and I'm able to see the snap assist borders for the outside halves of the screens, but not the inside (i.e. I can make a vertical half window on the right side of the right screen, and left side of the left screen, but there's no snap assist for the inner halves).

**Comment by emvaized** [comment]
I believe I could not reproduce this issue — assist shows for inner halves for me just fine:
![Screenshot_30-10-22_02-25](https://user-images.githubusercontent.com/37851576/198856098-b1971a45-f35b-4465-aa99-c55837154aeb.png)

Maybe you have some unusual monitors setup, which prevents proper detection of window coordinates?

**Comment by Victor239** [comment]
I have two 1920x1080 monitors, I'm not sure what might be unusual about them: https://youtu.be/JMwsKGPXOwg

System specs:
![](https://i.imgur.com/0NkVcje.png)

**Comment by emvaized** [comment]
I see. Then, your issue is not with the script, but with the window snapping mechanism in KDE itself.

In order to snap window to the inner side on multi-monitor setup, you have to slowly drag it to the edge between screens, and then wait a little bit — like this: 
![snap](https://user-images.githubusercontent.com/37851576/199111124-d6c2c7d8-53ef-42c0-b31a-064894fa322a.gif)

**Comment by Victor239** [comment]
Ohhhh, nice that works for me, thanks! It would be helpful if users could adjust the sensitivity of this to make it a bit easier e.g. making it so that 0-200 pixels away from edge can trigger the assist.

**Comment by emvaized** [comment]
You'd have to address this request to KDE Plasma devs, this script has nothing to do with these settings

**Comment by Victor239** [comment]
Ah, okay. Do you know what setting it is?

**Comment by emvaized** [comment]
There is no such setting. I mean, it must be somewhere in system under the hood, but currently no option for user to easily change it
