### ISSUE TITLE
Cannot set colors in settings

### ISSUE THREAD

**Issue by G2-Games** [emvaized/kde-snap-assist#7]
I don't know if this is an issue with the script, or with KDE, but I cannot set the colors in the system settings for the script:
![image](https://user-images.githubusercontent.com/72430668/183961315-54fb7c20-6402-4ffc-bf98-d1dbf707783b.png)

**Comment by emvaized** [comment]
Hmm, that's weird! 

Did you tried re-login in Plasma, disabling/enabling the script? Are you able to set any color for these inputs, and then see the updated colors in the Snap Assist after re-enabling the script?

**Comment by G2-Games** [comment]
I have re-logged, disabled/enabled, and nothing has changed, even after updating. Additionally, setting the colors in the config file works fine, so I don't know what's up.

**Comment by G2-Games** [comment]
Update: The configs reset and turn the colors back to black after reboot

I have a feeling this is an issue with my system and not this script

**Comment by emvaized** [comment]
Yeah, I have the same feeling. Could not imagine how ColorButton element for a "string" config could get the boolean "false" value.
